# 测试环境配置

# JWT配置
security:
  jwt:
    token:
      # 测试环境使用专门的密钥
      secret-key: ${JWT_SECRET:test_environment_secret_key_for_jwt_token}
      expire-length: 86400000  # 24小时
      refresh-expire-length: 2592000000  # 30天

# 服务器配置
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    # 测试环境数据库，使用独立的测试库
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.100}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:lawfirm_test}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:test_user}
    password: ${MYSQL_PASSWORD:test_password}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      
  # 测试环境可以启用缓存
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s

# 日志配置
logging:
  level:
    root: info
    com.lawfirm.lawfirmserver: info
    org.springframework.jdbc.core.JdbcTemplate: info
  file:
    name: logs/lawfirm-server-test.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 15 