# Spring配置
spring:
  # 多环境配置
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  application:
    name: lawfirm-server
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 事务管理配置
  transaction:
    default-timeout: 30s
    rollback-on-commit-failure: true

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Dao.xml
  type-aliases-package: com.lawfirm.lawfirmserver.**.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    default-statement-timeout: 30
    default-fetch-size: 100

# JWT配置
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:your_secret_key_here_at_least_32_chars}
      expire-length: ${JWT_EXPIRE:86400000}  # 24小时
      refresh-expire-length: ${JWT_REFRESH_EXPIRE:2592000000}  # 30天

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 300
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.lawfirm.lawfirmserver: debug
    org.springframework.jdbc: debug


