# JWT配置
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:your_secret_key_here_at_least_32_chars}
      expire-length: ${JWT_EXPIRE:86400000}  # 24小时
      refresh-expire-length: ${JWT_REFRESH_EXPIRE:2592000000}  # 30天

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 300
    min-spare-threads: 30

# Spring配置
spring:
  application:
    name: lawfirm-server
  
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:5001}/${MYSQL_DATABASE:lawfirm}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    # Hikari连接池配置
    hikari:
      # 连接池名称
      pool-name: HikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  
  # 事务管理配置
  transaction:
    default-timeout: 30s
    rollback-on-commit-failure: true
    
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.lawfirm.lawfirmserver.**.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    default-statement-timeout: 30
    default-fetch-size: 100

# 日志配置
logging:
  level:
    root: info
    com.lawfirm.lawfirmserver: debug
    org.springframework.jdbc.core.JdbcTemplate: debug 